library('tidyverse')
library('ggpubr')
library('rstatix')
library('broom')

#compute zscores for pain data
MLpain_old_vol_outlier$GCPS_Characteristic_Pain_Intensity_Avg_c <- scale(MLpain_old_vol_outlier$GCPS_Characteristic_Pain_Intensity_Avg, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$GCPS_Disability_Avg_c <- scale(MLpain_old_vol_outlier$GCPS_Disability_Avg, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$mri_pain_duration_c <- scale(MLpain_old_vol_outlier$mri_pain_duration, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$Temporal_Summation_Thenar_c <- scale(MLpain_old_vol_outlier$Temporal_Summation_Thenar, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$Temporal_Summation_Metatarsal_c <- scale(MLpain_old_vol_outlier$Temporal_Summation_Metatarsal, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$PPT_Quad_Average_c <- scale(MLpain_old_vol_outlier$PPT_Quad_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$PPT_Trap_Average_c <- scale(MLpain_old_vol_outlier$PPT_Trap_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$Pinprick_Thenar_c <- scale(MLpain_old_vol_outlier$Pinprick_Thenar, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$Pinprick_Metatarsal_c <- scale(MLpain_old_vol_outlier$Pinprick_Metatarsal, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$VDT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$VDT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$VDT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$VDT_Metatarsal_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$WDT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$WDT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$WDT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$WDT_Metatarsal_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$HPT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$HPT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$HPT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$HPT_Metatarsal_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$CDT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$CDT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$CDT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$CDT_Metatarsal_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$CPT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$CPT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$CPT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$CPT_Metatarsal_Average, center=TRUE, scale=TRUE)

#invert direction of cold detection and pain scores and add to heat detection and pain for combined thermal detection and pain variables
MLpain_old_vol_outlier$CDT_Thenar_Average_r <- -(MLpain_old_vol_outlier$CDT_Thenar_Average_c)
MLpain_old_vol_outlier$CDT_Metatarsal_Average_r <- -(MLpain_old_vol_outlier$CDT_Metatarsal_Average_c)
MLpain_old_vol_outlier$CPT_Thenar_Average_r <- -(MLpain_old_vol_outlier$CPT_Thenar_Average_c)
MLpain_old_vol_outlier$CPT_Metatarsal_Average_r <- -(MLpain_old_vol_outlier$CPT_Metatarsal_Average_c)

MLpain_old_vol_outlier$Thermal_Detection_Thenar <- MLpain_old_vol_outlier$CDT_Thenar_Average_r + MLpain_old_vol_outlier$WDT_Thenar_Average_c
MLpain_old_vol_outlier$Thermal_Detection_Metatarsal <- MLpain_old_vol_outlier$CDT_Metatarsal_Average_r + MLpain_old_vol_outlier$WDT_Metatarsal_Average_c
MLpain_old_vol_outlier$Thermal_Pain_Thenar <- MLpain_old_vol_outlier$CPT_Thenar_Average_r + MLpain_old_vol_outlier$HPT_Thenar_Average_c
MLpain_old_vol_outlier$Thermal_Pain_Metatarsal <- MLpain_old_vol_outlier$CPT_Metatarsal_Average_r + MLpain_old_vol_outlier$HPT_Metatarsal_Average_c


MLpain_old_vol_outlier$TotalCerebellarVol <- (MLpain_old_vol_outlier$Left_Cerebellum_Cortex + MLpain_old_vol_outlier$Right_Cerebellum_Cortex + MLpain_old_vol_outlier$Left_Cerebellum_White_Matter + MLpain_old_vol_outlier$Right_Cerebellum_White_Matter)

intensity_int.aov <- anova_test(formula = GCPS_Characteristic_Pain_Intensity_Avg_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
disability_int.aov <- anova_test(formula = GCPS_Disability_Avg_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
duration_int.aov <- anova_test(formula = mri_pain_duration_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
summationthe_int.aov <- anova_test(formula = Temporal_Summation_Thenar_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
summationmet_int.aov <- anova_test(formula = Temporal_Summation_Metatarsal_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
pptquad_int.aov <- anova_test(formula = PPT_Quad_Average_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
ppttrap_int.aov <- anova_test(formula = PPT_Trap_Average_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
pinprickthe_int.aov <- anova_test(formula = Pinprick_Thenar_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
pinprickmet_int.aov <- anova_test(formula = Pinprick_Metatarsal_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
vdtthe_int.aov <- anova_test(formula = VDT_Thenar_Average_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
vdtmet_int.aov <- anova_test(formula = VDT_Metatarsal_Average_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
tdtthe_int.aov <- anova_test(formula = Thermal_Detection_Thenar ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
tdtmet_int.aov <- anova_test(formula = Thermal_Detection_Metatarsal ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
tptthe_int.aov <- anova_test(formula = Thermal_Pain_Thenar ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
tptmet_int.aov <- anova_test(formula = Thermal_Pain_Metatarsal ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
puncthe_int.aov <- anova_test(formula = Punctate_Thenar_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)
puncmet_int.aov <- anova_test(formula = Punctate_Metatarsal_c ~ EstimatedTotalIntraCranialVol + TotalCerebellarVol * Gender, data = MLpain_old_vol_outlier)


get_anova_table(intensity_int.aov)
get_anova_table(disability_int.aov)
get_anova_table(duration_int.aov)
get_anova_table(summationthe_int.aov)
get_anova_table(summationmet_int.aov)
get_anova_table(pptquad_int.aov)
get_anova_table(ppttrap_int.aov)
get_anova_table(pinprickthe_int.aov)
get_anova_table(pinprickmet_int.aov)
get_anova_table(vdtthe_int.aov)
get_anova_table(vdtmet_int.aov)
get_anova_table(tdtthe_int.aov)
get_anova_table(tdtmet_int.aov)
get_anova_table(tptthe_int.aov)
get_anova_table(tptmet_int.aov)
get_anova_table(puncthe_int.aov)
get_anova_table(puncmet_int.aov)


library('sjstats')

anova_stats(intensity_int.aov, digits=3)
anova_stats(disability_int.aov, digits=3)
anova_stats(duration_int.aov, digits=3)
anova_stats(summationthe_int.aov, digits=3)
anova_stats(summationmet_int.aov, digits=3)
anova_stats(pptquad_int.aov, digits=3)
anova_stats(ppttrap_int.aov, digits=3)
anova_stats(pinprickthe_int.aov, digits=3)
anova_stats(pinprickmet_int.aov, digits=3)
anova_stats(vdtthe_int.aov, digits=3)
anova_stats(vdtmet_int.aov, digits=3)
anova_stats(tdtthe_int.aov, digits=3)
anova_stats(tdtmet_int.aov, digits=3)
anova_stats(tptthe_int.aov, digits=3)
anova_stats(tptmet_int.aov, digits=3)
anova_stats(puncthe_int.aov, digits=3)
anova_stats(puncmet_int.aov, digits=3)
