MLpain_old_vol_outlier$TotalCerebellarVol <- (MLpain_old_vol_outlier$Left_Cerebellum_Cortex + MLpain_old_vol_outlier$Right_Cerebellum_Cortex + MLpain_old_vol_outlier$Left_Cerebellum_White_Matter + MLpain_old_vol_outlier$Right_Cerebellum_White_Matter)

intensity_int.aov <- aov(formula = GCPS_Characteristic_Pain_Intensity_Avg ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
disability_int.aov <- aov(formula = GCPS_Disability_Avg ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
summationthe_int.aov <- aov(formula = Temporal_Summation_Thenar_c ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
summationmet_int.aov <- aov(formula = Temporal_Summation_Metatarsal_c ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
pptquad_int.aov <- aov(formula = PPT_Quad_Average_c ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
ppttrap_int.aov <- aov(formula = PPT_Trap_Average_c ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
pinprickthe_int.aov <- aov(formula = Pinprick_Thenar_c ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
pinprickmet_int.aov <- aov(formula = Pinprick_Metatarsal_c ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
vdtthe_int.aov <- aov(formula = VDT_Thenar_Average_c ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
vdtmet_int.aov <- aov(formula = VDT_Metatarsal_Average_c ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
tdtthe_int.aov <- aov(formula = Thermal_Detection_Thenar ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
tdtmet_int.aov <- aov(formula = Thermal_Detection_Metatarsal ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
tptthe_int.aov <- aov(formula = Thermal_Pain_Thenar ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)
tptmet_int.aov <- aov(formula = Thermal_Pain_Metatarsal ~ TotalCerebellarVol * Chronological_Age * Gender, data = MLpain_old_vol_outlier)

summary(intensity_int.aov)
summary(disability_int.aov)
summary(summationthe_int.aov)
summary(summationmet_int.aov)
summary(pptquad_int.aov)
summary(ppttrap_int.aov)
summary(pinprickthe_int.aov)
summary(pinprickmet_int.aov)
summary(vdtthe_int.aov)
summary(vdtmet_int.aov)
summary(tdtthe_int.aov)
summary(tdtmet_int.aov)
summary(tptthe_int.aov)
summary(tptmet_int.aov)

library('sjstats')

anova_stats(intensity_int.aov, digits=3)
anova_stats(disability_int.aov, digits=3)
anova_stats(summationthe_int.aov, digits=3)
anova_stats(summationmet_int.aov, digits=3)
anova_stats(pptquad_int.aov, digits=3)
anova_stats(ppttrap_int.aov, digits=3)
anova_stats(pinprickthe_int.aov, digits=3)
anova_stats(pinprickmet_int.aov, digits=3)
anova_stats(vdtthe_int.aov, digits=3)
anova_stats(vdtmet_int.aov, digits=3)
anova_stats(tdtthe_int.aov, digits=3)
anova_stats(tdtmet_int.aov, digits=3)
anova_stats(tptthe_int.aov, digits=3)
anova_stats(tptmet_int.aov, digits=3)
