library('tidyverse')
library('ggpubr')
library('rstatix')
library('broom')
library('lm.beta')
library('yarrr')

#compute zscores for pain data
Pain_volume$GCPS_Characteristic_Pain_Intensity_Avg_c <- scale(Pain_volume$GCPS_Characteristic_Pain_Instensity_Avg, center=TRUE, scale=TRUE)
Pain_volume$GCPS_Disability_Avg_c <- scale(Pain_volume$GCPS_Disability_Avg, center=TRUE, scale=TRUE)
Pain_volume$mri_pain_duration_c <- scale(Pain_volume$mri_pain_duration, center=TRUE, scale=TRUE)
Pain_volume$Temporal_Summation_Thenar_c <- scale(Pain_volume$Temporal_Summation_Thenar, center=TRUE, scale=TRUE)
Pain_volume$Temporal_Summation_Metatarsal_c <- scale(Pain_volume$Temporal_Summation_Metatarsal, center=TRUE, scale=TRUE)
Pain_volume$PPT_Quad_Average_c <- scale(Pain_volume$PPT_Quad_Average, center=TRUE, scale=TRUE)
Pain_volume$PPT_Trap_Average_c <- scale(Pain_volume$PPT_Trap_Average, center=TRUE, scale=TRUE)
Pain_volume$VDT_Thenar_Average_c <- scale(Pain_volume$VDT_Thenar_Average, center=TRUE, scale=TRUE)
Pain_volume$VDT_Metatarsal_Average_c <- scale(Pain_volume$VDT_Metatarsal_Average, center=TRUE, scale=TRUE)
Pain_volume$WDT_Thenar_Average_c <- scale(Pain_volume$WDT_Thenar_Average, center=TRUE, scale=TRUE)
Pain_volume$WDT_Metatarsal_Average_c <- scale(Pain_volume$WDT_Metatarsal_Average, center=TRUE, scale=TRUE)
Pain_volume$HPT_Thenar_Average_c <- scale(Pain_volume$HPT_Thenar_Average, center=TRUE, scale=TRUE)
Pain_volume$HPT_Metatarsal_Average_c <- scale(Pain_volume$HPT_Metatarsal_Average, center=TRUE, scale=TRUE)
Pain_volume$CDT_Thenar_Average_c <- scale(Pain_volume$CDT_Thenar_Average, center=TRUE, scale=TRUE)
Pain_volume$CDT_Metatarsal_Average_c <- scale(Pain_volume$CDT_Metatarsal_Average, center=TRUE, scale=TRUE)
Pain_volume$CPT_Thenar_Average_c <- scale(Pain_volume$CPT_Thenar_Average, center=TRUE, scale=TRUE)
Pain_volume$CPT_Metatarsal_Average_c <- scale(Pain_volume$CPT_Metatarsal_Average, center=TRUE, scale=TRUE)
Pain_volume$CPM_c <- scale(Pain_volume$CPM, center=TRUE, scale=TRUE)

#invert direction of cold detection and pain scores and add to heat detection and pain for combined thermal detection and pain variables
Pain_volume$CDT_Thenar_Average_r <- -(Pain_volume$CDT_Thenar_Average_c)
Pain_volume$CDT_Metatarsal_Average_r <- -(Pain_volume$CDT_Metatarsal_Average_c)
Pain_volume$CPT_Thenar_Average_r <- -(Pain_volume$CPT_Thenar_Average_c)
Pain_volume$CPT_Metatarsal_Average_r <- -(Pain_volume$CPT_Metatarsal_Average_c)

Pain_volume$Thermal_Detection_Thenar <- Pain_volume$CDT_Thenar_Average_r + Pain_volume$WDT_Thenar_Average_c
Pain_volume$Thermal_Detection_Metatarsal <- Pain_volume$CDT_Metatarsal_Average_r + Pain_volume$WDT_Metatarsal_Average_c
Pain_volume$Thermal_Pain_Thenar <- Pain_volume$CPT_Thenar_Average_r + Pain_volume$HPT_Thenar_Average_c
Pain_volume$Thermal_Pain_Metatarsal <- Pain_volume$CPT_Metatarsal_Average_r + Pain_volume$HPT_Metatarsal_Average_c


#perform multiple linear regression analyses with covariates for older adults
intensity_c_Older.lm <- lm(formula = GCPS_Characteristic_Pain_Intensity_Avg_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
disability_c_Older.lm <- lm(formula = GCPS_Disability_Avg_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
duration_c_Older.lm <- lm(formula = mri_pain_duration_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
summationthe_c_Older.lm <- lm(formula = Temporal_Summation_Thenar_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
summationmet_c_Older.lm <- lm(formula = Temporal_Summation_Metatarsal_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
pptquad_c_Older.lm <- lm(formula = PPT_Quad_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
ppttrap_c_Older.lm <- lm(formula = PPT_Trap_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
vdtthe_c_Older.lm <- lm(formula = VDT_Thenar_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
vdtmet_c_Older.lm <- lm(formula = VDT_Metatarsal_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
tdtthe_c_Older.lm <- lm(formula = Thermal_Detection_Thenar ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
tdtmet_c_Older.lm <- lm(formula = Thermal_Detection_Metatarsal ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
tptthe_c_Older.lm <- lm(formula = Thermal_Pain_Thenar ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
tptmet_c_Older.lm <- lm(formula = Thermal_Pain_Metatarsal ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")
cpm_c_Older.lm <- lm(formula = CPM_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Older")

#show results tables
summary(intensity_c_Older.lm)
summary(disability_c_Older.lm)
summary(duration_c_Older.lm)
summary(summationthe_c_Older.lm)
summary(summationmet_c_Older.lm)
summary(pptquad_c_Older.lm)
summary(ppttrap_c_Older.lm)
summary(vdtthe_c_Older.lm)
summary(vdtmet_c_Older.lm)
summary(tdtthe_c_Older.lm)
summary(tdtmet_c_Older.lm)
summary(tptthe_c_Older.lm)
summary(tptmet_c_Older.lm)
summary(cpm_c_Older.lm)

#get betas for regression models using lm.beta package
lm.beta(intensity_c_Older.lm)
lm.beta(disability_c_Older.lm)
lm.beta(duration_c_Older.lm)
lm.beta(summationthe_c_Older.lm)
lm.beta(summationmet_c_Older.lm)
lm.beta(pptquad_c_Older.lm)
lm.beta(ppttrap_c_Older.lm)
lm.beta(vdtthe_c_Older.lm)
lm.beta(vdtmet_c_Older.lm)
lm.beta(tdtthe_c_Older.lm)
lm.beta(tdtmet_c_Older.lm)
lm.beta(tptthe_c_Older.lm)
lm.beta(tptmet_c_Older.lm)
lm.beta(cpm_c_Older.lm)

#perform multiple linear regression analyses with covariates for older adults
intensity_c_Younger.lm <- lm(formula = GCPS_Characteristic_Pain_Intensity_Avg_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
disability_c_Younger.lm <- lm(formula = GCPS_Disability_Avg_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
duration_c_Younger.lm <- lm(formula = mri_pain_duration_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
summationthe_c_Younger.lm <- lm(formula = Temporal_Summation_Thenar_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
summationmet_c_Younger.lm <- lm(formula = Temporal_Summation_Metatarsal_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
pptquad_c_Younger.lm <- lm(formula = PPT_Quad_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
ppttrap_c_Younger.lm <- lm(formula = PPT_Trap_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
vdtthe_c_Younger.lm <- lm(formula = VDT_Thenar_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
vdtmet_c_Younger.lm <- lm(formula = VDT_Metatarsal_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
tdtthe_c_Younger.lm <- lm(formula = Thermal_Detection_Thenar ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
tdtmet_c_Younger.lm <- lm(formula = Thermal_Detection_Metatarsal ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
tptthe_c_Younger.lm <- lm(formula = Thermal_Pain_Thenar ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
tptmet_c_Younger.lm <- lm(formula = Thermal_Pain_Metatarsal ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")
cpm_c_Younger.lm <- lm(formula = CPM_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = Pain_volume, subset = Age_Group == "Younger")

#show results tables
summary(intensity_c_Younger.lm)
summary(disability_c_Younger.lm)
summary(duration_c_Younger.lm)
summary(summationthe_c_Younger.lm)
summary(summationmet_c_Younger.lm)
summary(pptquad_c_Younger.lm)
summary(ppttrap_c_Younger.lm)
summary(vdtthe_c_Younger.lm)
summary(vdtmet_c_Younger.lm)
summary(tdtthe_c_Younger.lm)
summary(tdtmet_c_Younger.lm)
summary(tptthe_c_Younger.lm)
summary(tptmet_c_Younger.lm)
summary(cpm_c_Younger.lm)

#get betas for regression models using lm.beta package
lm.beta(intensity_c_Younger.lm)
lm.beta(disability_c_Younger.lm)
lm.beta(duration_c_Younger.lm)
lm.beta(summationthe_c_Younger.lm)
lm.beta(summationmet_c_Younger.lm)
lm.beta(pptquad_c_Younger.lm)
lm.beta(ppttrap_c_Younger.lm)
lm.beta(vdtthe_c_Younger.lm)
lm.beta(vdtmet_c_Younger.lm)
lm.beta(tdtthe_c_Younger.lm)
lm.beta(tdtmet_c_Younger.lm)
lm.beta(tptthe_c_Younger.lm)
lm.beta(tptmet_c_Younger.lm)
lm.beta(cpm_c_Younger.lm)
