#compute zscores for pain data
MLpain_old_vol_outlier$GCPS_Characteristic_Pain_Intensity_Avg_c <- scale(MLpain_old_vol_outlier$GCPS_Characteristic_Pain_Intensity_Avg, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$GCPS_Disability_Avg_c <- scale(MLpain_old_vol_outlier$GCPS_Disability_Avg, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$mri_pain_duration_c <- scale(MLpain_old_vol_outlier$mri_pain_duration, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$Temporal_Summation_Thenar_c <- scale(MLpain_old_vol_outlier$Temporal_Summation_Thenar, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$Temporal_Summation_Metatarsal_c <- scale(MLpain_old_vol_outlier$Temporal_Summation_Metatarsal, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$PPT_Quad_Average_c <- scale(MLpain_old_vol_outlier$PPT_Quad_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$PPT_Trap_Average_c <- scale(MLpain_old_vol_outlier$PPT_Trap_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$Pinprick_Thenar_c <- scale(MLpain_old_vol_outlier$Pinprick_Thenar, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$Pinprick_Metatarsal_c <- scale(MLpain_old_vol_outlier$Pinprick_Metatarsal, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$VDT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$VDT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$VDT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$VDT_Metatarsal_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$WDT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$WDT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$WDT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$WDT_Metatarsal_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$HPT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$HPT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$HPT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$HPT_Metatarsal_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$CDT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$CDT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$CDT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$CDT_Metatarsal_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$CPT_Thenar_Average_c <- scale(MLpain_old_vol_outlier$CPT_Thenar_Average, center=TRUE, scale=TRUE)
MLpain_old_vol_outlier$CPT_Metatarsal_Average_c <- scale(MLpain_old_vol_outlier$CPT_Metatarsal_Average, center=TRUE, scale=TRUE)

#invert direction of cold detection and pain scores and add to heat detection and pain for combined thermal detection and pain variables
MLpain_old_vol_outlier$CDT_Thenar_Average_r <- -(MLpain_old_vol_outlier$CDT_Thenar_Average_c)
MLpain_old_vol_outlier$CDT_Metatarsal_Average_r <- -(MLpain_old_vol_outlier$CDT_Metatarsal_Average_c)
MLpain_old_vol_outlier$CPT_Thenar_Average_r <- -(MLpain_old_vol_outlier$CPT_Thenar_Average_c)
MLpain_old_vol_outlier$CPT_Metatarsal_Average_r <- -(MLpain_old_vol_outlier$CPT_Metatarsal_Average_c)

MLpain_old_vol_outlier$Thermal_Detection_Thenar <- MLpain_old_vol_outlier$CDT_Thenar_Average_r + MLpain_old_vol_outlier$WDT_Thenar_Average_c
MLpain_old_vol_outlier$Thermal_Detection_Metatarsal <- MLpain_old_vol_outlier$CDT_Metatarsal_Average_r + MLpain_old_vol_outlier$WDT_Metatarsal_Average_c
MLpain_old_vol_outlier$Thermal_Pain_Thenar <- MLpain_old_vol_outlier$CPT_Thenar_Average_r + MLpain_old_vol_outlier$HPT_Thenar_Average_c
MLpain_old_vol_outlier$Thermal_Pain_Metatarsal <- MLpain_old_vol_outlier$CPT_Metatarsal_Average_r + MLpain_old_vol_outlier$HPT_Metatarsal_Average_c

#perform multiple linear regression analyses with covariates
intensity_c.lm <- lm(formula = GCPS_Characteristic_Pain_Intensity_Avg_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
disability_c.lm <- lm(formula = GCPS_Disability_Avg_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
duration_c.lm <- lm(formula = mri_pain_duration_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
summationthe_c.lm <- lm(formula = Temporal_Summation_Thenar_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
summationmet_c.lm <- lm(formula = Temporal_Summation_Metatarsal_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
pptquad_c.lm <- lm(formula = PPT_Quad_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
ppttrap_c.lm <- lm(formula = PPT_Trap_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
pinprickthe_c.lm <- lm(formula = Pinprick_Thenar_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
pinprickmet_c.lm <- lm(formula = Pinprick_Metatarsal_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
vdtthe_c.lm <- lm(formula = VDT_Thenar_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
vdtmet_c.lm <- lm(formula = VDT_Metatarsal_Average_c ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
tdtthe_c.lm <- lm(formula = Thermal_Detection_Thenar ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
tdtmet_c.lm <- lm(formula = Thermal_Detection_Metatarsal ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
tptthe_c.lm <- lm(formula = Thermal_Pain_Thenar ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
tptmet_c.lm <- lm(formula = Thermal_Pain_Metatarsal ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)

#show results tables
summary(intensity_c.lm)
summary(disability_c.lm)
summary(duration_c.lm)
summary(summationthe_c.lm)
summary(summationmet_c.lm)
summary(pptquad_c.lm)
summary(ppttrap_c.lm)
summary(pinprickthe_c.lm)
summary(pinprickmet_c.lm)
summary(vdtthe_c.lm)
summary(vdtmet_c.lm)
summary(tdtthe_c.lm)
summary(tdtmet_c.lm)
summary(tptthe_c.lm)
summary(tptmet_c.lm)

#get betas for regression models using lm.beta package
library('lm.beta')

lm.beta(intensity_c.lm)
lm.beta(disability_c.lm)
lm.beta(duration_c.lm)
lm.beta(summationthe_c.lm)
lm.beta(summationmet_c.lm)
lm.beta(pptquad_c.lm)
lm.beta(ppttrap_c.lm)
lm.beta(pinprickthe_c.lm)
lm.beta(pinprickmet_c.lm)
lm.beta(vdtthe_c.lm)
lm.beta(vdtmet_c.lm)
lm.beta(tdtthe_c.lm)
lm.beta(tdtmet_c.lm)
lm.beta(tptthe_c.lm)
lm.beta(tptmet_c.lm)
