summationthe.lm <- lm(formula = Temporal_Summation_Thenar ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
summationmet.lm <- lm(formula = Temporal_Summation_Metatarsal ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
pptquad.lm <- lm(formula = PPT_Quad_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
ppttrap.lm <- lm(formula = PPT_Trap_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
pinprickthe.lm <- lm(formula = Pinprick_Thenar ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
pinprickmet.lm <- lm(formula = Pinprick_Metatarsal ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
vdtthe.lm <- lm(formula = VDT_Thenar_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
vdtmet.lm <- lm(formula = VDT_Metatarsal_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
wdtthe.lm <- lm(formula = WDT_Thenar_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
wdtmet.lm <- lm(formula = WDT_Metatarsal_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
hptthe.lm <- lm(formula = HPT_Thenar_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
hptmet.lm <- lm(formula = HPT_Metatarsal_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
cdtthe.lm <- lm(formula = CDT_Thenar_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
cdtmet.lm <- lm(formula = CDT_Metatarsal_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
cptthe.lm <- lm(formula = CPT_Thenar_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)
cptmet.lm <- lm(formula = CPT_Metatarsal_Average ~ Left_Cerebellum_Cortex + Right_Cerebellum_Cortex + Left_Cerebellum_White_Matter + Right_Cerebellum_White_Matter + EstimatedTotalIntraCranialVol + Chronological_Age + EHI_Score + CES_D_Score + Gender, data = MLpain_old_vol_outlier)

summary(summationthe.lm)
summary(summationmet.lm)
summary(pptquad.lm)
summary(ppttrap.lm)
summary(pinprickthe.lm)
summary(pinprickmet.lm)
summary(vdtthe.lm)
summary(vdtmet.lm)
summary(wdtthe.lm)
summary(wdtmet.lm)
summary(hptthe.lm)
summary(hptmet.lm)
summary(cdtthe.lm)
summary(cdtmet.lm)
summary(cptthe.lm)
